#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PI_GEN_DIR="${1:-${PI_GEN_DIR:-}}"

if [ -z "$PI_GEN_DIR" ]; then
  echo "usage: $0 /path/to/pi-gen" >&2
  echo "or set PI_GEN_DIR=/path/to/pi-gen" >&2
  exit 2
fi

if [ ! -d "$PI_GEN_DIR" ]; then
  echo "pi-gen directory does not exist: $PI_GEN_DIR" >&2
  exit 1
fi

STAGE_SRC="$SCRIPT_DIR/pi-gen/stage-web-spectrometer"
STAGE_DEST="$PI_GEN_DIR/stage-web-spectrometer"
FILES_DEST="$STAGE_DEST/00-install/files"

random_password() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(18))
PY
}

rsync -a --delete "$STAGE_SRC/" "$STAGE_DEST/"
mkdir -p "$FILES_DEST/app"

rsync -a --delete --delete-excluded \
  --exclude ".git" \
  --exclude ".venv" \
  --exclude "__pycache__" \
  --exclude ".pytest_cache" \
  --exclude "build" \
  --exclude "release" \
  --exclude "desktop" \
  --exclude "ui" \
  --exclude "web" \
  --exclude "os-build-call.txt" \
  --exclude "custom-os/pi-gen/stage-web-spectrometer/00-install/files/app" \
  "$REPO_DIR/" \
  "$FILES_DEST/app/"

install -Dm755 \
  "$SCRIPT_DIR/firstboot/web-spectrometer-firstboot" \
  "$FILES_DEST/web-spectrometer-firstboot"

install -Dm644 \
  "$SCRIPT_DIR/firstboot/web-spectrometer-firstboot.service" \
  "$FILES_DEST/web-spectrometer-firstboot.service"

install -Dm644 \
  "$SCRIPT_DIR/systemd/web-spectrometer.service" \
  "$FILES_DEST/web-spectrometer.service"

if [ ! -f "$PI_GEN_DIR/config" ]; then
  cp "$SCRIPT_DIR/pi-gen/config.example" "$PI_GEN_DIR/config"
  RANDOM_PASS="$(random_password)"
  {
    echo
    echo "# Generated by custom-os/prepare-pi-gen-stage.sh for a non-interactive appliance image."
    echo "FIRST_USER_PASS='$RANDOM_PASS'"
  } >> "$PI_GEN_DIR/config"
  echo "Created $PI_GEN_DIR/config from custom-os/pi-gen/config.example"
fi

if grep -Eq "^DISABLE_FIRST_BOOT_USER_RENAME=['\"]?1['\"]?$" "$PI_GEN_DIR/config" \
  && ! grep -q "^FIRST_USER_PASS=" "$PI_GEN_DIR/config"; then
  RANDOM_PASS="$(random_password)"
  {
    echo
    echo "# Generated by custom-os/prepare-pi-gen-stage.sh for a non-interactive appliance image."
    echo "FIRST_USER_PASS='$RANDOM_PASS'"
  } >> "$PI_GEN_DIR/config"
  echo "Added FIRST_USER_PASS to $PI_GEN_DIR/config"
fi

if grep -q "Generated by custom-os/prepare-pi-gen-stage.sh" "$PI_GEN_DIR/config"; then
  if grep -q "^DEPLOY_COMPRESSION='xz'$" "$PI_GEN_DIR/config"; then
    sed -i "s/^DEPLOY_COMPRESSION='xz'$/DEPLOY_COMPRESSION='none'/" "$PI_GEN_DIR/config"
    sed -i "/^COMPRESSION_LEVEL='1'$/d" "$PI_GEN_DIR/config"
    echo "Updated $PI_GEN_DIR/config so build-image.sh packages the release artifact."
  fi
fi

if ! grep -q "^export BOOTSTRAP_NO_CHECK_SIG=" "$PI_GEN_DIR/config"; then
  {
    echo
    echo "# Current Raspbian bootstrap signatures can trip modern GPG SHA1 binding policy."
    echo "# Keep this limited to debootstrap's initial Release check."
    echo "export BOOTSTRAP_NO_CHECK_SIG=1"
  } >> "$PI_GEN_DIR/config"
  echo "Added BOOTSTRAP_NO_CHECK_SIG to $PI_GEN_DIR/config"
fi

echo "Prepared pi-gen stage at $STAGE_DEST"
echo "Using pi-gen config at $PI_GEN_DIR/config"
